### ISSUE TITLE
Add gallery VM

### ISSUE THREAD

**Issue by spelltwister** [Microsoft/vsts-image-generation#67] opened 2018-02-05 23:15 UTC
Is it possible to have some automation that can just update an azure gallery VM so we don't have to build it from packer.  Would be nice if we could just pick "Build Server 2017" from the azure gallery.

**Comment by bryanmacfarlane** [comment] 2018-02-05 23:16
Dupe of: https://github.com/Microsoft/vsts-image-generation/issues/64

reasoning is there.

packer is the automation ...

**Closed by bryanmacfarlane** 2018-02-05 23:16 UTC

**Comment by spelltwister** [comment] 2018-02-07 17:46
that's not what the linked item says.  it's due to not being able to redistro?  Seems strange.  Lets see... packer takes 8.5hrs to run, creating a VM from an image takes... minutes?

**Comment by chrisrpatterson** [comment] 2018-02-16 19:41
@spelltwister this is a gallery VM for Visual Studio 2017 that you can spin up on Auzre.

**Comment by spelltwister** [comment] 2018-02-17 16:15
and that's not even close to the same thing as the hosted build.  but seems like you really do not want to publish something to gallery and there may be legal concerns so I'm just going to build out my own build server image.  sorry for wasting your time!

**Comment by lokesh755** [comment] 2018-02-17 16:32
Btw you can disable steps like Antivirus scan and remove software you may not use from the packer template which might fasten the build process , since you are concerned about the build time.
